### ISSUE TITLE
add MINECRAFT_VERSION_NETWORK

### ISSUE THREAD

**Issue by Driesboy** [PeratX/BetaTester#1]

**Comment by PeratX** [comment]
What ???

**Comment by Driesboy** [comment]
Wait i am at school now

**Comment by Driesboy** [comment]
http://minecraftpocket-servers.com/server/35077/

19132  work
19133 work for 0.14.0 but he say 0.13.1 in this website

**Comment by Driesboy** [comment]
http://minecraftpocket-servers.com/server/35077/

19132 work
19133 work for 0.14.0 but he say 0.13.1 in this website

**Comment by PeratX** [comment]
@Driesboy roger that.

**Comment by Driesboy** [comment]
thx
