### ISSUE TITLE
Players dont move?

### ISSUE THREAD

**Issue by haniokasai** [PeratX/BetaTester#2]
it seems that players dont move and blocks wernt  update.
is this bug?

**Comment by haniokasai** [comment]
https://copy.com/SZIdSqxM3iPOZpqv

**Comment by SirGamer** [comment]
0.14 players do NOT move on a 0.13 client's screen.

**Comment by PeratX** [comment]
Will check

**Comment by PeratX** [comment]
@haniokasai @SirGamer @Driesboy Try the new version

**Comment by SirGamer** [comment]
K.

**Comment by Driesboy** [comment]
not fixed
