### ISSUE TITLE
0.14.0 Build 4 

### ISSUE THREAD

**Issue by flaxues** [PeratX/BetaTester#7]
0.14.0 Build 4 is not working for me. Is it already supported?

**Comment by flaxues** [comment]
With Build 3 or 4 I can't join i'm getting the error 'Your MCPE client is outdated'

**Comment by Driesboy** [comment]
same

**Comment by Driesboy** [comment]
i try to fix

**Comment by flaxues** [comment]
Build 5 is already out

https://t.co/jK5TcwENFo

**Comment by PeratX** [comment]
Will fix. I have found the problem

**Comment by Driesboy** [comment]
Ok
